//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renta_Autos_SAS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentaAutosEntities : DbContext
    {
        public RentaAutosEntities()
            : base("name=RentaAutosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuarios> Clientes { get; set; }
        public virtual DbSet<RegistroAuto> RegistroAuto { get; set; }
        public virtual DbSet<RentaAutos> RentaAutos { get; set; }
        public virtual DbSet<TipoDeAuto> TipoDeAuto { get; set; }
    }
}
