//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renta_Autos_SAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroAuto
    {
        public RegistroAuto()
        {
            this.RentaAutos = new HashSet<RentaAutos>();
        }
    
        public int Id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string NumeroDePasajeros { get; set; }
        public string Kilometraje { get; set; }
        public Nullable<int> IdTipoDeAuto { get; set; }
    
        public virtual TipoDeAuto TipoDeAuto { get; set; }
        public virtual ICollection<RentaAutos> RentaAutos { get; set; }
    }
}
