//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renta_Autos_SAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentaAutos
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaDeRenta { get; set; }
        public Nullable<System.DateTime> FechaDeEntrega { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
    
        public virtual Usuarios Clientes { get; set; }
        public virtual RegistroAuto RegistroAuto { get; set; }
    }
}
